[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python main.py"
