version: '3.8'

services:
  video-downloader-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./.env:/app/.env
    environment:
      - STORAGE_DIR=/app/downloads
      - CLEANUP_INTERVAL_HOURS=2
      - HOST=0.0.0.0
      - PORT=8000
      - MAX_FILE_SIZE_MB=500
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

