services:
  - type: web
    name: infinity-hole-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main_simple.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
