name: video_downloader
description: A cross-platform video downloader app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_downloader: ^1.11.5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

